### ISSUE TITLE
Meal / Food Tracker

### ISSUE THREAD

**Issue by rhit-villencr** [avichaljadeja2002/omni-planner#7]
- [x] Create Prototype (2 hrs)
- [x] Send Prototype to client for confirmation
- [x] Implement in code (2 hrs)
- [x] Reviewed prototype with client (0.3 hrs)
- [x] Implemented changes in code (2 hrs)
- [x] Connected backend (1 hr)
- [ ] Review With Client

Currently, my meal planner & food tracker are two separate apps, make it so that there is a combination of these two put together on one page and a grocery list page that is populated by the meals' ingredients.

**Comment by rhit-siahmasf** [comment]
Can we also add the grocery list that is populated by the meal(s) ingredients? Let me know if things like this need to have their own story instead. I think a method of grouping related stories will be helpful for making design decisions as well.
